AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  ApiGatewayDevelop:
    Type: AWS::Serverless::Api
    Properties:
      StageName: develop
  JavaSnapstartFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: br.com.likwi.snapstart.LambdaHandler::handleRequest
      Runtime: java21
      AutoPublishAlias: develop
      SnapStart:
        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        javasnapstart:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayDevelop
            Path: /{proxy+}
            Method: ANY